"""
config.py — FINAL PRODUCTION CONFIG
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# -------------------------------
# 🔹 BASE PATHS
# -------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

PROMPTS_DIR = BASE_DIR / "prompts"
OUTPUTS_DIR = BASE_DIR / "outputs"
IMAGES_DIR = OUTPUTS_DIR / "images"

OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
IMAGES_DIR.mkdir(parents=True, exist_ok=True)


# -------------------------------
# 🔹 ENV MODES
# -------------------------------

ENV = os.getenv("ENV", "dev")  # dev | prod
DEBUG = ENV == "dev"


# -------------------------------
# 🔹 LLM CONFIG
# -------------------------------

SUPPORTED_PROVIDERS = {"openai", "anthropic", "gemini"}

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "anthropic").lower()

if LLM_PROVIDER not in SUPPORTED_PROVIDERS:
    raise ValueError(f"Invalid LLM_PROVIDER: {LLM_PROVIDER}")


LLM_MODELS = {
    "openai": os.getenv("OPENAI_MODEL", "gpt-4o"),
    "anthropic": os.getenv("ANTHROPIC_MODEL", "claude-opus-4-5"),
    "gemini": os.getenv("GEMINI_MODEL", "gemini-1.5-pro"),
}


# -------------------------------
# 🔹 API KEYS
# -------------------------------

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


def _validate_keys():
    if LLM_PROVIDER == "openai" and not OPENAI_API_KEY:
        raise ValueError("Missing OPENAI_API_KEY")

    if LLM_PROVIDER == "anthropic" and not ANTHROPIC_API_KEY:
        raise ValueError("Missing ANTHROPIC_API_KEY")

    if LLM_PROVIDER == "gemini" and not GEMINI_API_KEY:
        raise ValueError("Missing GEMINI_API_KEY")


_validate_keys()


# -------------------------------
# 🔹 PIPELINE SETTINGS
# -------------------------------

MAX_TOKENS = int(os.getenv("MAX_TOKENS", "4096"))

# 🔥 Adaptive token control
if ENV == "prod":
    MAX_TOKENS = min(MAX_TOKENS, 3000)

TEMPERATURE = float(os.getenv("TEMPERATURE", "0.2"))

IMAGE_DPI = int(os.getenv("IMAGE_DPI", "150"))

MIN_IMAGE_WIDTH = int(os.getenv("MIN_IMAGE_WIDTH", "100"))
MIN_IMAGE_HEIGHT = int(os.getenv("MIN_IMAGE_HEIGHT", "100"))


# -------------------------------
# 🔹 REPORT CONFIG
# -------------------------------

REPORT_TITLE = "Detailed Diagnostic Report (DDR)"
REPORT_FOOTER = "Generated by DDR AI System — Confidential"
COMPANY_NAME = os.getenv("COMPANY_NAME", "Site Inspection Services")


# -------------------------------
# 🔹 LOGGING
# -------------------------------

LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG" if DEBUG else "INFO")


# -------------------------------
# 🔹 FAILSAFE (IMPORTANT)
# -------------------------------

def get_active_model():
    """
    Returns model safely with fallback
    """
    model = LLM_MODELS.get(LLM_PROVIDER)

    if not model:
        return "gpt-4o"

    return model