"""
config.py — FINAL FIXED VERSION (STREAMLIT + LOCAL SAFE)
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env for local
load_dotenv()

# Try Streamlit secrets
try:
    import streamlit as st
except:
    st = None


# -------------------------------
# 🔹 ENV HELPER (DEFINE FIRST)
# -------------------------------

def get_env(key, default=None):
    if st and key in st.secrets:
        return st.secrets[key]
    return os.getenv(key, default)


# -------------------------------
# 🔹 BASE PATHS
# -------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

PROMPTS_DIR = BASE_DIR / "prompts"
OUTPUTS_DIR = BASE_DIR / "outputs"
IMAGES_DIR = OUTPUTS_DIR / "images"

OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
IMAGES_DIR.mkdir(parents=True, exist_ok=True)


# -------------------------------
# 🔹 ENV MODE
# -------------------------------

ENV = get_env("ENV", "dev")
DEBUG = ENV == "dev"


# -------------------------------
# 🔹 LLM CONFIG
# -------------------------------

SUPPORTED_PROVIDERS = {"openai", "anthropic", "gemini"}

LLM_PROVIDER = get_env("LLM_PROVIDER", "gemini").lower()

if LLM_PROVIDER not in SUPPORTED_PROVIDERS:
    raise ValueError(f"Invalid LLM_PROVIDER: {LLM_PROVIDER}")


LLM_MODELS = {
    "openai": get_env("OPENAI_MODEL", "gpt-4o"),
    "anthropic": get_env("ANTHROPIC_MODEL", "claude-opus-4-5"),
    "gemini": get_env("GEMINI_MODEL", "gemini-1.5-pro"),
}


# -------------------------------
# 🔹 API KEYS
# -------------------------------

OPENAI_API_KEY = get_env("OPENAI_API_KEY")
ANTHROPIC_API_KEY = get_env("ANTHROPIC_API_KEY")
GEMINI_API_KEY = get_env("GEMINI_API_KEY")


def _validate_keys():
    if LLM_PROVIDER == "openai" and not OPENAI_API_KEY:
        raise ValueError("Missing OPENAI_API_KEY")

    if LLM_PROVIDER == "anthropic" and not ANTHROPIC_API_KEY:
        raise ValueError("Missing ANTHROPIC_API_KEY")

    if LLM_PROVIDER == "gemini" and not GEMINI_API_KEY:
        raise ValueError("Missing GEMINI_API_KEY")


_validate_keys()


# -------------------------------
# 🔹 PIPELINE SETTINGS
# -------------------------------

MAX_TOKENS = int(get_env("MAX_TOKENS", "4096"))

if ENV == "prod":
    MAX_TOKENS = min(MAX_TOKENS, 3000)

TEMPERATURE = float(get_env("TEMPERATURE", "0.2"))

IMAGE_DPI = int(get_env("IMAGE_DPI", "150"))

MIN_IMAGE_WIDTH = int(get_env("MIN_IMAGE_WIDTH", "100"))
MIN_IMAGE_HEIGHT = int(get_env("MIN_IMAGE_HEIGHT", "100"))


# -------------------------------
# 🔹 REPORT CONFIG
# -------------------------------

REPORT_TITLE = "Detailed Diagnostic Report (DDR)"
REPORT_FOOTER = "Generated by DDR AI System — Confidential"
COMPANY_NAME = get_env("COMPANY_NAME", "Site Inspection Services")


# -------------------------------
# 🔹 LOGGING
# -------------------------------

LOG_LEVEL = get_env("LOG_LEVEL", "DEBUG" if DEBUG else "INFO")


# -------------------------------
# 🔹 FAILSAFE
# -------------------------------

def get_active_model():
    return LLM_MODELS.get(LLM_PROVIDER, "gpt-4o")